version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es_data:/var/lib/elasticsearch
      - ./es_config/elasticsearch.yml:/etc/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - docker-elk

  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    networks:
      - docker-elk
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

networks:
  docker-elk: