version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4G -Xmx4G"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es_data:/var/lib/elasticsearch
      - ./es_config/elasticsearch.yml:/etc/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - docker-elk

  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    networks:
      - docker-elk
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_CACHE_MEMORY=8G
      - NEO4J_HEAP_MEMORY=32G
      - NEO4J_AUTH=neo4j/somesafepassword
    ports:
     - "7474:7474"
     - "7687:7687"
    volumes:
     - ./db:/data
    cap_add:
     - SYS_RESOURCE

networks:
  docker-elk: